spring:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
  datasource:
    url: jdbc:h2:mem:debt;
    username: sa
  flyway:
    url: jdbc:h2:mem:debt;DB_CLOSE_DELAY=-1
    baseline-on-migrate: true
server:
  port: 8012